[package]
name = "get_bilibili_favlist_bvid_list"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
favlist_core = { path = "../favlist_core" }
indicatif = "0.17"
